package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.mybatis.model.Album;
import lt.vu.mybatis.model.AlbumContributor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AlbumContributorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_CONTRIBUTOR
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_CONTRIBUTOR
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    int insert(AlbumContributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_CONTRIBUTOR
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    AlbumContributor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_CONTRIBUTOR
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    List<AlbumContributor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_CONTRIBUTOR
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    int updateByPrimaryKey(AlbumContributor record);
}