package lt.vu.mybatis.model;

import java.util.List;

public class Artist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    private String name;

    private List<AlbumContributor> albumContributors;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.ID
     *
     * @return the value of PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.ID
     *
     * @param id the value for PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.NAME
     *
     * @return the value of PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.NAME
     *
     * @param name the value for PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<AlbumContributor> getAlbums(){return this.albumContributors;};
}