package lt.vu.mybatis.model;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    private Integer albumId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.TITLE
     *
     * @return the value of PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.TITLE
     *
     * @param title the value for PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @return the value of PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @param albumId the value for PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 21 18:53:42 EEST 2020
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }
}